//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalProfits.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPasswordToken
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public System.Guid Token { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsUsed { get; set; }
    }
}
